application: remote-access-app
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /screenshare
  static_dir: screenshare

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /.*
  script: main.app

inbound_services:
- channel_presence

libraries:
- name: jinja2
  version: latest